### ISSUE TITLE
Scroll-to-top functionality

### ISSUE THREAD

**Issue by akwiatek** [CJSCommonPlatform/ngSkeletonApp#15]
There is a need in our application for a scroll-to-top functionality.
Whenever there are error messages displayed at the top of the page the page should be scrolled up so the user can read them. That seems to be generic functionality which may come useful to other apps based on the skeleton and I reckon it would be good if the skeleton had a piece of code for that, e.g. a directive doing the scroll when a submit button is scrolled.

**Comment by fabiotisci** [comment]
Hi Adam,

I've included a redirection to the top each time that a state changes, so that'll solve the problem you mentioned. 

Check routes.service.js
      $rootScope.$on('$stateChangeSuccess', function () {
         ...  
        $location.hash($stateParams.scrollTo);
        $anchorScroll();
      });
