### ISSUE TITLE
Copy Fonts task is not working properly

### ISSUE THREAD

**Issue by mszygenda** [CJSCommonPlatform/ngSkeletonApp#4]
Hi,

I noticed that copy-fonts task isn't working properly (it's not copying any fonts from any of the bower dependencies)

The reason for that is the task "copy-fonts" is using "main-bower-files" plugin which provides list of main entry points for any bower component. The problem is that entry points for bower components are JS files and not *.ttf and other font files, hence the copy-fonts effectively does nothing. 

In the end some fonts are missing when application is run (eg. font-awesome)

**Comment by CJSCommonPlatform** [comment]
@fabiotisci can you take a look please :-)

**Comment by fabiotisci** [comment]
There was a bug in the destination. The bower configuration can be changed to include also the destination of the fonts. That's mainly to avoid copying files that we might not be interested, Otherwise we could just remove bowerfiles from that gulp task and just copy all the fonts across.

**Comment by fabiotisci** [comment]
In bower.json include:

"overrides": {
    "font-awesome": {
      "main": [
        "less/font-awesome.less",
        "scss/font-awesome.scss",
        "fonts/_._"
      ]
    },
    "ng-gov-uk": {
      "main": [
        "dist/ngGovUk.min.js",
        "dist/ngGovUk.less",
        "dist/assets/fonts/_._"
      ]
    },
    "bootstrap": {
      "main": [
        "less/bootstrap.less",
        "dist/js/bootstrap.js",
        "dist/fonts/_._"
      ]
    },
