### ISSUE TITLE
OcLazyLoad should be disabled in production

### ISSUE THREAD

**Issue by mszygenda** [CJSCommonPlatform/ngSkeletonApp#6]
If you run 

gulp --production

It'll minify and bundle all JS files in app-HASH.min.js, vendor-HASH-min.js. These files get loaded when application start but ocLazyLoad will load each individual controller in unminified format once again.

Steps:
1. gulp --production
2. gulp serve
3. Open browser
4. Notice there's request for app-HASH-.min.js and another one for index.controller.js

Way to solve it is to introduce some config property in the build so that if it's production config-routes.js assumes dependencies are loaded and doesn't call ocLazyLoad.

**Comment by mszygenda** [comment]
Hm, actually when you get rid of the plugin in production app won't work. There's something wrong with order of components in bundled JS.

To get that working in prod mode you'll have to call $ocLazyLoad.inject(DEPENDENCIES_MODULE_NAMES); manually instead of list $ocLazyLoad.inject({ files })

The thing is that in current skeleton we don't have those dependencies listed in routes.json

**Comment by mszygenda** [comment]
Have a look at:

https://github.com/CJSCommonPlatform/ngSkeletonApp/pull/7

**Comment by jamesbirrellgray** [comment]
Can @fabiotisci come down?

**Comment by jamesbirrellgray** [comment]
Also what's Adam's surname, I'm locked out my Sopra email

**Comment by mszygenda** [comment]
I am not in the office today. But I'll be tomorrow if you want to discuss it.

**Comment by fabiotisci** [comment]
There was a bug in the production gulp task that was including all the files, so lazy loading was basically useless. This has been now fixed.

Just essential files are combined and loaded on index, the rest of files are uglyfied and minified but nor combined and are loaded using lazy loading.

The change is just in the gulp folder, so it should not affect your code.
