### ISSUE TITLE
Low test coverage

### ISSUE THREAD

**Issue by akwiatek** [CJSCommonPlatform/ngSkeletonApp#8]
Add the moment only approx. 8% of branches are test covered. Please create additional unit tests so the code will have better test coverage. 

$ gulp test
[09:13:41] Using gulpfile ~/workspaces/moj/ngSkeletonApp/gulpfile.js
[09:13:42] Starting 'lint'...
[09:13:42] Analysing source with ESLint
[09:13:42] Finished 'lint' after 574 ms
[09:13:42] Starting 'test'...
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket 32GmdovCR6zJ7M8hW1Tc with id 42822763
WARN [web-server]: 404: /app/config/app.config.json
PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 4 of 4 SUCCESS (0.01 secs / 0.022 secs)

=============================== Coverage summary ===============================
Statements   : 70.34% ( 83/118 )
Branches     : 7.69% ( 1/13 )
Functions    : 56.6% ( 30/53 )
# Lines        : 70.34% ( 83/118 )

[09:13:44] Karma completed!
[09:13:44] Finished 'test' after 2.34 s

**Comment by fabiotisci** [comment]
There was quite a lot of refactoring in order to improve test coverage

=============================== Coverage summary ===============================
Statements   : 87.22% ( 116/133 )
Branches     : 92.31% ( 12/13 )
Functions    : 75.44% ( 43/57 )
Lines        : 87.22% ( 116/133 )
