### ISSUE TITLE
ng-html2js plugin warning

### ISSUE THREAD

**Issue by akwiatek** [CJSCommonPlatform/ngSkeletonApp#9]
A warning is thrown when 5a0e2c75d5d4bc4fa18049cedfdd74288ecdc804 commit is used.

$ gulp test
[11:19:00] Using gulpfile ~/workspaces/moj/ngSkeletonApp/gulpfile.js
[11:19:00] Starting 'lint'...
[11:19:00] Analysing source with ESLint
[11:19:01] Finished 'lint' after 505 ms
[11:19:01] Starting 'test'...
WARN [preprocess]: Can not load "ng-html2js", it is not registered!
  Perhaps you are missing some plugin?
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/

**Comment by fabiotisci** [comment]
have you done npm update?

**Comment by akwiatek** [comment]
The problem is still there after I have re-downloaded dependencies.

``` bash
rm -rf bower_components node_modules dist
npm install
bower install
gulp
gulp
gulp test
```

**Comment by fabiotisci** [comment]
do you have the folder 'karma-ng-html2js-preprocessor' in node_modules?

**Comment by fabiotisci** [comment]
in gulp.config.js your karmaPlugins value should look like this:
karmaPlugins: ['karma-jasmine', 'karma-coverage', 'karma-phantomjs-launcher', 'karma-chrome-launcher', 'karma-sinon', 'karma-junit-reporter', 'karma-ng-html2js-preprocessor'],
